apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo
        image: amitarmittal/flaskyolo:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  type: NodePort
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30200
